server:
  port: 8082

spring:
  application:
    name: middle-roadmap
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console  # Mở console tại http://localhost:8082/h2-console
  jpa:
    hibernate:
#      ddl-auto: create-drop   # Tạo hoặc cập nhật schema tự động
      ddl-auto: update
    show-sql: true       # Hiển thị SQL trong log
    open-in-view: true

api:
  prefix: /api

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-validity-in-seconds: 86400

springdoc:
  api-docs:
    path: /middle-roadmap/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
  swagger-ui:
    path: /middle-roadmap/swagger-ui.html