FROM confluentinc/cp-kafka-connect:7.6.0
RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.5.4
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:14.0.7
